# Generated by Django 3.2.16 on 2023-11-07 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VerbForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original', models.CharField(max_length=100, verbose_name='original verb')),
                ('translation', models.CharField(default='', max_length=1024, verbose_name='translation')),
                ('is_regular', models.BooleanField(default=False, verbose_name='if the verb is "regelmäßig"')),
                ('past_form', models.CharField(max_length=100, verbose_name='präteritum form')),
                ('participle', models.CharField(max_length=100, verbose_name='partizip 2 form')),
                ('level', models.CharField(max_length=5, verbose_name='on which level this word should be learned')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='this word was created at')),
            ],
        ),
    ]
